### ISSUE TITLE
.NET framework error when installing on XP

### ISSUE THREAD

**Issue by suan** [suan/mirlite#1]
Leo informed me of getting a "mir:lite cannot be installed in systems with net framework version 3.5 or smaller." error message when trying to install on Windows XP. Persisted even after installing .NET 3.5

**Comment by efeloefelo** [comment]
and whats up- how i do fix the bug, i got dotnet4 and what could i do to make the system run   

btw: you are a super cool guy, thx alot for your fascination and engagement for these tec

**Comment by suan** [comment]
@efeloefelo Apparently you still need to install .NET 3.5, even if you already have 4.0 installed. Let me know if that still doesn't work.

**Comment by suan** [comment]
@efeloefelo Has this worked out for you? If so I want to close this issue.
